### GET A DIRECTOR PAGE
GET http://localhost:8090/directors/?pageSize=20&pageNumber=0

### GET A WRONG DIRECTOR PAGE NUMBER
GET http://localhost:8090/directors/?pageSize=20&pageNumber=23098

### GET A PAGE WITH WRONG TOO BIG OF PAGE SIZE
GET http://localhost:8090/directors/?pageSize=12022598209&pageNumber=0

### GET DIRECTOR BY ID
GET http://localhost:8090/directors/00135d3a-a528-4637-ba78-87204e18e5e8

#docker run --rm --name postgres -p 5433:5432 -e POSTGRES_PASSWORD=123 postgres

### CREATE A NEW DIRECTOR
POST http://localhost:8090/directors/
Content-Type: application/json

{
  "name": "Joe Rogan",
  "net_worth": 4.4
}

### UPDATE DIRECTOR BY ID
PUT http://localhost:8090/directors/00eb7a7e-6145-4dd2-b74b-30f799e6d32f
Content-Type: application/json

{
  "name": "Jeff Jefferson",
  "net_worth": 4.2
}

### DELETE DIRECTOR BY ID
DELETE http://localhost:8090/directors/00eb7a7e-6145-4dd2-b74b-30f799e6d32f


### GET TOP MOVIES BY REVENUE
GET http://localhost:8090/directors/directorsByNetWorth?top_n=6
